[build]
  publish = "."
  command = "echo Build complete"

[[redirects]]
  from = "/spa-website.html"
  to = "/spa-website.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
